---
title: "Best no bake power bars"
subtitle: "Quick breakfast that was one of my daily drivers"
date: "2023-08-26"
categories: [food]
---
These bars are a quick and simple solution for breakfast. I usually keep ingredients on hand and throw things together on the weekend. Adapted and original credit from [darebee.com](http://darebee.com/recipes/homemade-no-bake-protein-bars.html).

#### Stuffs
 - 1 jar of TJ's unsalted smooth almond butter
 - 4 scoops of TJ's vanilla whey protein powder
 - 1 tbs of ground cinnamon 
 - 1 can of TJ's organic coconut milk (or you can use their coconut cream which is thicker)
 - 2.5 cups of TJ's gluten free quick oats
 - Some dried cranberries and/or roasted coconut flakes if you'd like

#### Make directions
 - Add coconut cream, protein powder, cinnamon first in a bowl and mix till smooth
 - Add whole jar of almond butter and mix in completely
 - Add Oats until things start to resemble cookies
 - Add in your mixins if you'd like, cranberries and a little roasted coconut flakes are my usual
 -  Line a 9x13in pyrex with wax paper and place the power bar mix on top
 - Even everything out, cover and place in the fridge for ~4 hours
 - After everything has hardened you can remove it from the dish and cut into desired squares
 - Wrap each one individually in wax paper and store in a large plastic bag in the fridge