project:
  type: website

website:
  title: "Maybeno"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mmaybeno
      - icon: linkedin
        href: https://www.linkedin.com/in/mattmaybeno/
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css



