project:
  type: website

website:
  title: "Maybeno"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mmaybeno
      - icon: linkedin
        href: https://www.linkedin.com/in/mattmaybeno/
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    include-in-header:
      - text: |
          <script async defer data-website-id="acd24912-f9b4-4a75-94a6-ed2ed4e130c6" src="https://mwm.ninja/umami.js"></script>



